apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8snetpolicy-backend-chart.fullname" . }}-policy
spec:
  podSelector:
    matchLabels:
      {{- include "k8snetpolicy-backend-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}  
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-
    ports:
    - protocol: TCP
      port: 8080 