apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-app-service
spec:
  selector:
    app: {{ .Release.Name }}-backend-app
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 3000
  type: ClusterIP
