apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-policy
spec:
  podSelector:
    matchLabels:
      app: k8snetpolicy-backend-backend-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: k8snetpolicy-frontend-chart
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: k8snetpolicy-backend-mysql
    ports:
    - protocol: TCP
      port: 3306
