apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerhub.secretName }}
  namespace: default  
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.dockerhub.username }}
  password: {{ .Values.dockerhub.password }}