apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: k8snetpolicy-frontend-chart
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector: {} 
    ports:
    - protocol: TCP
      port: 80 
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: k8snetpolicy-backend-backend-app
    ports:
    - protocol: TCP
      port: 8080
