version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build: .
    image: pabhi4881/k8snetpolicy-backend:latest
    container_name: backend
    restart: always
    ports: 
      - "3000:3000"  # Changed from 3000 to 5000
    environment:
      PORT: 3000
      DB_HOST: mysql  
      DB_PORT: 3306    
      DB_NAME: todo_db
      DB_USER: root    
      DB_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - app-network

  app:
    build: ./public
    image: pabhi4881/k8snetpolicy-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
